image: gradle:jdk11

stages:
  - build
  - analysis
  - verification

build:
  stage: build
  script:
    - gradle build

version-check:
  stage: analysis
  script:
    - java -version
    - gradle --version

test-coverage:
  stage: analysis
  script:
    - gradle test jacocoTestReport
    - gradle jacocoTestCoverageVerification
  artifacts:
    paths: build/reports/jacoco/test/jacocoTestReport.xml

checkstyle-main:
  stage: analysis
  script:
    - gradle checkStyleMain
  artifacts:
    paths: build/reports/checkstyle/main.xml

checkstyle-test:
  stage: analysis
  script:
    - gradle checkStyleTest
  artifacts:
    paths: build/reports/checkstyle/test.xm

testing:
  stage: analysis
  script:
    - gradle test
  artifacts:
    reports:
      junit: build/reports/tests/testReport.html
  