image: gradle:jdk11

stages:
  - build
  - analysis

build:
  stage: build
  script:
    - gradle build

version-check:
  stage: analysis
  script:
    - java -version
    - gradle --version

test-coverage:
  stage: analysis
  script:
    - gradle test jacocoTestReport
  artifacts:
    reports:
      junit: build/reports/jacoco/test/jacocoTestReport.xml

checkstyle-main:
  stage: analysis
  script:
    - gradle checkStyleMain
  artifacts:
    reports:
      junit: build/reports/checkstyle/main.xml

checkstyle-test:
  stage: analysis
  script:
    - gradle checkStyleTest
  artifacts:
    reports:
      junit: build/reports/checkstyle/test.xml