/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OOP_Proj;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestClass {
    @Test public void test() {
        
    }
}
